# Generated by Django 5.1.6 on 2025-02-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('shift', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wing', models.CharField(max_length=15)),
                ('beds', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
