# Generated by Django 5.1.6 on 2025-02-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0004_apointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apointment',
            new_name='Appointment',
        ),
    ]
