# Generated by Django 5.1.6 on 2025-02-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediapp', '0007_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='contact2',
        ),
    ]
